(this.webpackJsonpterminaltalha = this.webpackJsonpterminaltalha || []).push([
  [0],
  {
    36: function (i, a, e) {},
    37: function (i, a, e) {},
    39: function (i, a, e) {},
    40: function (i, a, e) {},
    43: function (i, a, e) {
      "use strict";
      e.r(a);
      var n = e(10),
        s = e.n(n),
        t = e(31),
        r = e.n(t),
        m = (e(36), e(37), e(22)),
        k = e.n(m),
        o = e(1),
        c = function () {
          return Object(o.jsxs)(k.a, {
            children: [
              Object(o.jsx)("p", { children: "Welcome guest!" }),
              Object(o.jsx)("p", {
                children: "See available commands with --help",
              }),
            ],
          });
        },
        l = (e(39), e(11)),
        u =
          (e(40),
          [
            "abaza",
            "abazan",
            "ag",
            "a\u011fz\u0131na s\u0131\xe7ay\u0131m",
            "ahmak",
            "allah",
            "allahs\u0131z",
            "am",
            "amar\u0131m",
            "ambiti",
            "am biti",
            "amc\u0131\u011f\u0131",
            "amc\u0131\u011f\u0131n",
            "amc\u0131\u011f\u0131n\u0131",
            "amc\u0131\u011f\u0131n\u0131z\u0131",
            "amc\u0131k",
            "amc\u0131k ho\u015faf\u0131",
            "amc\u0131klama",
            "amc\u0131kland\u0131",
            "amcik",
            "amck",
            "amckl",
            "amcklama",
            "amcklaryla",
            "amckta",
            "amcktan",
            "amcuk",
            "am\u0131k",
            "am\u0131na",
            "am\u0131nako",
            "am\u0131na koy",
            "am\u0131na koyar\u0131m",
            "am\u0131na koyay\u0131m",
            "am\u0131nakoyim",
            "am\u0131na koyyim",
            "am\u0131na s",
            "am\u0131na sikem",
            "am\u0131na sokam",
            "am\u0131n feryad\u0131",
            "am\u0131n\u0131",
            "am\u0131n\u0131 s",
            "am\u0131n oglu",
            "am\u0131no\u011flu",
            "am\u0131n o\u011flu",
            "am\u0131s\u0131na",
            "am\u0131s\u0131n\u0131",
            "amina",
            "amina g",
            "amina k",
            "aminako",
            "aminakoyarim",
            "amina koyarim",
            "amina koyay\u0131m",
            "amina koyayim",
            "aminakoyim",
            "aminda",
            "amindan",
            "amindayken",
            "amini",
            "aminiyarraaniskiim",
            "aminoglu",
            "amin oglu",
            "amiyum",
            "amk",
            "amkafa",
            "amk \xe7ocu\u011fu",
            "amlarnzn",
            "aml\u0131",
            "amm",
            "ammak",
            "ammna",
            "amn",
            "amna",
            "amnda",
            "amndaki",
            "amngtn",
            "amnn",
            "amona",
            "amq",
            "ams\u0131z",
            "amsiz",
            "amsz",
            "amteri",
            "amugaa",
            "amu\u011fa",
            "amuna",
            "ana",
            "anaaann",
            "anal",
            "analarn",
            "anam",
            "anamla",
            "anan",
            "anana",
            "anandan",
            "anan\u0131",
            "anan\u0131",
            "anan\u0131n",
            "anan\u0131n am",
            "anan\u0131n am\u0131",
            "anan\u0131n d\xf6l\xfc",
            "anan\u0131nki",
            "anan\u0131sikerim",
            "anan\u0131 sikerim",
            "anan\u0131sikeyim",
            "anan\u0131 sikeyim",
            "anan\u0131z\u0131n",
            "anan\u0131z\u0131n am",
            "anani",
            "ananin",
            "ananisikerim",
            "anani sikerim",
            "ananisikeyim",
            "anani sikeyim",
            "anann",
            "ananz",
            "anas",
            "anas\u0131n\u0131",
            "anas\u0131n\u0131n am",
            "anas\u0131 orospu",
            "anasi",
            "anasinin",
            "anay",
            "anayin",
            "angut",
            "anneni",
            "annenin",
            "annesiz",
            "anuna",
            "aptal",
            "aq",
            "a.q",
            "a.q.",
            "aq.",
            "ass",
            "atkafas\u0131",
            "atm\u0131k",
            "att\u0131rd\u0131\u011f\u0131m",
            "attrrm",
            "auzlu",
            "avrat",
            "ayklarmalrmsikerim",
            "azd\u0131m",
            "azd\u0131r",
            "azd\u0131r\u0131c\u0131",
            "babaannesi ka\u015far",
            "baban\u0131",
            "baban\u0131n",
            "babani",
            "babas\u0131 pezevenk",
            "baca\u011f\u0131na s\u0131\xe7ay\u0131m",
            "bac\u0131na",
            "bac\u0131n\u0131",
            "bac\u0131n\u0131n",
            "bacini",
            "bacn",
            "bacndan",
            "bacy",
            "bastard",
            "basur",
            "beyinsiz",
            "b\u0131z\u0131r",
            "bitch",
            "biting",
            "bok",
            "boka",
            "bokbok",
            "bok\xe7a",
            "bokhu",
            "bokkkumu",
            "boklar",
            "boktan",
            "boku",
            "bokubokuna",
            "bokum",
            "bombok",
            "boner",
            "bosalmak",
            "bo\u015falmak",
            "cenabet",
            "cibiliyetsiz",
            "cibilliyetini",
            "cibilliyetsiz",
            "cif",
            "cikar",
            "cim",
            "\xe7\xfck",
            "dalaks\u0131z",
            "dallama",
            "daltassak",
            "dalyarak",
            "dalyarrak",
            "dangalak",
            "dassagi",
            "diktim",
            "dildo",
            "dingil",
            "dingilini",
            "dinsiz",
            "dkerim",
            "domal",
            "domalan",
            "domald\u0131",
            "domald\u0131n",
            "domal\u0131k",
            "domal\u0131yor",
            "domalmak",
            "domalm\u0131\u015f",
            "domals\u0131n",
            "domalt",
            "domaltarak",
            "domalt\u0131p",
            "domalt\u0131r",
            "domalt\u0131r\u0131m",
            "domaltip",
            "domaltmak",
            "d\xf6l\xfc",
            "d\xf6nek",
            "d\xfcd\xfck",
            "eben",
            "ebeni",
            "ebenin",
            "ebeninki",
            "ebleh",
            "ecdad\u0131n\u0131",
            "ecdadini",
            "embesil",
            "emi",
            "fahise",
            "fahi\u015fe",
            "feri\u015ftah",
            "ferre",
            "fuck",
            "fucker",
            "fuckin",
            "fucking",
            "gavad",
            "gavat",
            "geber",
            "geberik",
            "gebermek",
            "gebermi\u015f",
            "gebertir",
            "ger\u0131zekal\u0131",
            "gerizekal\u0131",
            "gerizekali",
            "gerzek",
            "giberim",
            "giberler",
            "gibis",
            "gibi\u015f",
            "gibmek",
            "gibtiler",
            "goddamn",
            "godo\u015f",
            "godumun",
            "gotelek",
            "gotlalesi",
            "gotlu",
            "gotten",
            "gotundeki",
            "gotunden",
            "gotune",
            "gotunu",
            "gotveren",
            "goyiim",
            "goyum",
            "goyuyim",
            "goyyim",
            "g\xf6t",
            "g\xf6t deli\u011fi",
            "g\xf6telek",
            "g\xf6t herif",
            "g\xf6tlalesi",
            "g\xf6tlek",
            "g\xf6to\u011flan\u0131",
            "g\xf6t o\u011flan\u0131",
            "g\xf6to\u015f",
            "g\xf6tten",
            "g\xf6t\xfc",
            "g\xf6t\xfcn",
            "g\xf6t\xfcne",
            "g\xf6t\xfcnekoyim",
            "g\xf6t\xfcne koyim",
            "g\xf6t\xfcn\xfc",
            "g\xf6tveren",
            "g\xf6t veren",
            "g\xf6t verir",
            "gtelek",
            "gtn",
            "gtnde",
            "gtnden",
            "gtne",
            "gtten",
            "gtveren",
            "hasiktir",
            "hassikome",
            "hassiktir",
            "has siktir",
            "hassittir",
            "haysiyetsiz",
            "hayvan herif",
            "ho\u015faf\u0131",
            "h\xf6d\xfck",
            "hsktr",
            "huur",
            "\u0131bnel\u0131k",
            "ibina",
            "ibine",
            "ibinenin",
            "ibne",
            "ibnedir",
            "ibneleri",
            "ibnelik",
            "ibnelri",
            "ibneni",
            "ibnenin",
            "ibnerator",
            "ibnesi",
            "idiot",
            "idiyot",
            "imansz",
            "ipne",
            "iserim",
            "i\u015ferim",
            "ito\u011flu it",
            "kafam girsin",
            "kafas\u0131z",
            "kafasiz",
            "kahpe",
            "kahpenin",
            "kahpenin feryad\u0131",
            "kaka",
            "kaltak",
            "kanc\u0131k",
            "kancik",
            "kappe",
            "karhane",
            "ka\u015far",
            "kavat",
            "kavatn",
            "kaypak",
            "kayyum",
            "kerane",
            "kerhane",
            "kerhanelerde",
            "kevase",
            "keva\u015fe",
            "kevvase",
            "koca g\xf6t",
            "kodu\u011fmun",
            "kodu\u011fmunun",
            "kodumun",
            "kodumunun",
            "koduumun",
            "koyarm",
            "koyay\u0131m",
            "koyiim",
            "koyiiym",
            "koyim",
            "koyum",
            "koyyim",
            "krar",
            "kukudaym",
            "laciye boyad\u0131m",
            "lavuk",
            "libo\u015f",
            "madafaka",
            "mal",
            "malafat",
            "malak",
            "manyak",
            "mcik",
            "meme",
            "memelerini",
            "mezveleli",
            "minaamc\u0131k",
            "mincikliyim",
            "mna",
            "monakkoluyum",
            "motherfucker",
            "mudik",
            "oc",
            "ocuu",
            "ocuun",
            "O\xc7",
            "o\xe7",
            "o. \xe7ocu\u011fu",
            "o\u011flan",
            "o\u011flanc\u0131",
            "o\u011flu it",
            "orosbucocuu",
            "orospu",
            "orospucocugu",
            "orospu cocugu",
            "orospu \xe7oc",
            "orospu\xe7ocu\u011fu",
            "orospu \xe7ocu\u011fu",
            "orospu \xe7ocu\u011fudur",
            "orospu \xe7ocuklar\u0131",
            "orospudur",
            "orospular",
            "orospunun",
            "orospunun evlad\u0131",
            "orospuydu",
            "orospuyuz",
            "orostoban",
            "orostopol",
            "orrospu",
            "oruspu",
            "oruspu\xe7ocu\u011fu",
            "oruspu \xe7ocu\u011fu",
            "osbir",
            "ossurduum",
            "ossurmak",
            "ossuruk",
            "osur",
            "osurduu",
            "osuruk",
            "osururum",
            "otuzbir",
            "\xf6k\xfcz",
            "\xf6\u015fex",
            "patlak zar",
            "penis",
            "pezevek",
            "pezeven",
            "pezeveng",
            "pezevengi",
            "pezevengin evlad\u0131",
            "pezevenk",
            "pezo",
            "pic",
            "pici",
            "picler",
            "pi\xe7",
            "pi\xe7in o\u011flu",
            "pi\xe7 kurusu",
            "pi\xe7ler",
            "pipi",
            "pipi\u015f",
            "pisliktir",
            "porno",
            "pussy",
            "pu\u015ft",
            "pu\u015fttur",
            "rahminde",
            "revizyonist",
            "s1kerim",
            "s1kerm",
            "s1krm",
            "sakso",
            "saksofon",
            "salaak",
            "salak",
            "saxo",
            "sekis",
            "serefsiz",
            "sevgi koyar\u0131m",
            "sevi\u015felim",
            "sexs",
            "s\u0131\xe7ar\u0131m",
            "s\u0131\xe7t\u0131\u011f\u0131m",
            "s\u0131ecem",
            "sicarsin",
            "sie",
            "sik",
            "sikdi",
            "sikdi\u011fim",
            "sike",
            "sikecem",
            "sikem",
            "siken",
            "sikenin",
            "siker",
            "sikerim",
            "sikerler",
            "sikersin",
            "sikertir",
            "sikertmek",
            "sikesen",
            "sikesicenin",
            "sikey",
            "sikeydim",
            "sikeyim",
            "sikeym",
            "siki",
            "sikicem",
            "sikici",
            "sikien",
            "sikienler",
            "sikiiim",
            "sikiiimmm",
            "sikiim",
            "sikiir",
            "sikiirken",
            "sikik",
            "sikil",
            "sikildiini",
            "sikilesice",
            "sikilmi",
            "sikilmie",
            "sikilmis",
            "sikilmi\u015f",
            "sikilsin",
            "sikim",
            "sikimde",
            "sikimden",
            "sikime",
            "sikimi",
            "sikimiin",
            "sikimin",
            "sikimle",
            "sikimsonik",
            "sikimtrak",
            "sikin",
            "sikinde",
            "sikinden",
            "sikine",
            "sikini",
            "sikip",
            "sikis",
            "sikisek",
            "sikisen",
            "sikish",
            "sikismis",
            "siki\u015f",
            "siki\u015fen",
            "siki\u015fme",
            "sikitiin",
            "sikiyim",
            "sikiym",
            "sikiyorum",
            "sikkim",
            "sikko",
            "sikleri",
            "sikleriii",
            "sikli",
            "sikm",
            "sikmek",
            "sikmem",
            "sikmiler",
            "sikmisligim",
            "siksem",
            "sikseydin",
            "sikseyidin",
            "siksin",
            "siksinbaya",
            "siksinler",
            "siksiz",
            "siksok",
            "siksz",
            "sikt",
            "sikti",
            "siktigimin",
            "siktigiminin",
            "sikti\u011fim",
            "sikti\u011fimin",
            "sikti\u011fiminin",
            "siktii",
            "siktiim",
            "siktiimin",
            "siktiiminin",
            "siktiler",
            "siktim",
            "siktim",
            "siktimin",
            "siktiminin",
            "siktir",
            "siktir et",
            "siktirgit",
            "siktir git",
            "siktirir",
            "siktiririm",
            "siktiriyor",
            "siktir lan",
            "siktirolgit",
            "siktir ol git",
            "sittimin",
            "sittir",
            "skcem",
            "skecem",
            "skem",
            "sker",
            "skerim",
            "skerm",
            "skeyim",
            "skiim",
            "skik",
            "skim",
            "skime",
            "skmek",
            "sksin",
            "sksn",
            "sksz",
            "sktiimin",
            "sktrr",
            "skyim",
            "slaleni",
            "sokam",
            "sokar\u0131m",
            "sokarim",
            "sokarm",
            "sokarmkoduumun",
            "sokay\u0131m",
            "sokaym",
            "sokiim",
            "soktu\u011fumunun",
            "sokuk",
            "sokum",
            "soku\u015f",
            "sokuyum",
            "soxum",
            "sulaleni",
            "s\xfclaleni",
            "s\xfclalenizi",
            "s\xfcrt\xfck",
            "\u015ferefsiz",
            "\u015f\u0131ll\u0131k",
            "taaklarn",
            "taaklarna",
            "tarrakimin",
            "tasak",
            "tassak",
            "ta\u015fak",
            "ta\u015f\u015fak",
            "tipini s.k",
            "tipinizi s.keyim",
            "tiyniyat",
            "toplarm",
            "topsun",
            "toto\u015f",
            "vajina",
            "vajinan\u0131",
            "veled",
            "veledizina",
            "veled i zina",
            "verdiimin",
            "weled",
            "weledizina",
            "whore",
            "xikeyim",
            "yaaraaa",
            "yalama",
            "yalar\u0131m",
            "yalarun",
            "yaraaam",
            "yarak",
            "yaraks\u0131z",
            "yaraktr",
            "yaram",
            "yaraminbasi",
            "yaramn",
            "yararmorospunun",
            "yarra",
            "yarraaaa",
            "yarraak",
            "yarraam",
            "yarraam\u0131",
            "yarragi",
            "yarragimi",
            "yarragina",
            "yarragindan",
            "yarragm",
            "yarra\u011f",
            "yarra\u011f\u0131m",
            "yarra\u011f\u0131m\u0131",
            "yarraimin",
            "yarrak",
            "yarram",
            "yarramin",
            "yarraminba\u015f\u0131",
            "yarramn",
            "yarran",
            "yarrana",
            "yarrrak",
            "yavak",
            "yav\u015f",
            "yav\u015fak",
            "yav\u015fakt\u0131r",
            "yavu\u015fak",
            "y\u0131l\u0131\u015f\u0131k",
            "yilisik",
            "yogurtlayam",
            "yo\u011furtlayam",
            "yrrak",
            "z\u0131kk\u0131m\u0131m",
            "zibidi",
            "zigsin",
            "zikeyim",
            "zikiiim",
            "zikiim",
            "zikik",
            "zikim",
            "ziksiiin",
            "ziksiin",
            "zulliyetini",
            "zviyetini",
          ]),
        b = e.p + "static/media/nocurse.9a3539b9.jpg",
        d = e(21),
        y = e(26),
        h = e(27),
        j = Object(y.a)({
          apiKey: "AIzaSyDZskwhQ-xPnsEh3CIepMQr_T_4UAX4KIY",
          authDomain: "talhaio.firebaseapp.com",
          projectId: "talhaio",
          storageBucket: "talhaio.appspot.com",
          messagingSenderId: "392126831344",
          appId: "1:392126831344:web:16294bce8424afa5224035",
          measurementId: "G-TPY3W9HZHW",
        }),
        g = Object(h.a)(j),
        p = function i(a) {
          a.ref;
          var e = Object(n.useState)(""),
            s = Object(l.a)(e, 2),
            t = s[0],
            r = s[1],
            m = Object(n.useState)(!1),
            k = Object(l.a)(m, 2),
            c = k[0],
            y = k[1],
            h = [
              "https://youtu.be/bPoTKojgUhg?si=6F8g-sXpXeV14Cp-",
              "https://youtu.be/bPoTKojgUhg?si=6F8g-sXpXeV14Cp-",
            ],
            j = [
              {
                name: "Linkedin",
                url: "https://www.linkedin.com/in/talhajavedcom/",
              },
              { name: "Github", url: "https://github.com/talhajavedcom" },
              {
                name: "Instagram",
                url: "https://www.instagram.com/talhajavedcom/",
              },
            ];
          Object(n.useEffect)(function () {
            localStorage.hasOwnProperty("history") ||
              localStorage.setItem("history", JSON.stringify([]));
          }, []);
          var p = function (a) {
            if (u.includes(t))
              return Object(o.jsxs)(o.Fragment, {
                children: [
                  Object(o.jsx)("img", { src: b }),
                  Object(o.jsx)(i, {}),
                ],
              });
            if ("clear" === t)
              return window.location.reload(!0), Object(o.jsx)(o.Fragment, {});
            if ("instagram" === t)
              return (
                window.open(j[2].url, "_blank"),
                Object(o.jsx)(o.Fragment, { children: Object(o.jsx)(i, {}) })
              );
            if ("github" === t)
              return (
                window.open(j[1].url, "_blank"),
                Object(o.jsx)(o.Fragment, { children: Object(o.jsx)(i, {}) })
              );
            if ("linkedin" === t)
              return (
                window.open(j[0].url, "_blank"),
                Object(o.jsx)(o.Fragment, { children: Object(o.jsx)(i, {}) })
              );
            if ("resume easy" === t)
              return Object(o.jsxs)(o.Fragment, {
                children: [
                  Object(o.jsx)("p", {
                    children: "mail me for that contact.talhajaved@gmail.com",
                  }),
                  Object(o.jsx)("p", {
                    children: "contact.talhajaved@gmail.com",
                  }),
                  Object(o.jsx)(i, {}),
                ],
              });
            if ("resume hard" === t)
              return Object(o.jsxs)("div", {
                children: [
                  Object(o.jsx)("p", {
                    children: "contact.talhajaved@gmail.com",
                  }),
                  Object(o.jsx)(i, {}),
                ],
              });
            if ("about" === t)
              return Object(o.jsxs)(o.Fragment, {
                children: [
                  Object(o.jsx)("p", { children: "Yo" }),
                  Object(o.jsx)("p", {
                    children:
                      "I'm Talha Javed from Pakistan, currently working as a Freelancer",
                  }),
                  Object(o.jsx)(i, {}),
                ],
              });
            if ("whoami" === t)
              return Object(o.jsxs)(o.Fragment, {
                children: [
                  Object(o.jsx)("p", {
                    children: "I dont know who you are. Just guest.",
                  }),
                  Object(o.jsx)(i, {}),
                ],
              });
            if ("randommusic" === t)
              return Object(o.jsxs)(o.Fragment, {
                children: [
                  window.open(
                    h[Math.floor(Math.random() * h.length)],
                    "_blank"
                  ),
                  Object(o.jsx)(i, {}),
                ],
              });
            if ("randomjoke" === t)
              return Object(o.jsxs)(o.Fragment, {
                children: [
                  Object(o.jsx)("p", {
                    children: "Someone says im economist.",
                  }),
                  Object(o.jsx)(i, {}),
                ],
              });
            if ("--help" === t)
              return Object(o.jsxs)(o.Fragment, {
                children: [
                  Object(o.jsx)("p", { children: "here is list of commands" }),
                  Object(o.jsx)("p", {
                    children: "------------------------------------------",
                  }),
                  Object(o.jsx)("p", { children: "about" }),
                  Object(o.jsx)("p", { children: "whoami" }),
                  Object(o.jsx)("p", { children: "resume easy" }),
                  Object(o.jsx)("p", { children: "resume hard" }),
                  Object(o.jsx)("p", { children: "instagram" }),
                  Object(o.jsx)("p", { children: "github" }),
                  Object(o.jsx)("p", { children: "linkedin" }),
                  Object(o.jsx)("p", { children: "randomjoke" }),
                  Object(o.jsx)("p", { children: "randommusic" }),

                  Object(o.jsx)("p", { children: "clear" }),
                  Object(o.jsx)(i, {}),
                ],
              });
            if (t.includes("echo")) {
              var e = t.split(" ");
              return Object(o.jsxs)(o.Fragment, {
                children: [
                  Object(o.jsx)("p", {
                    children: e
                      .slice(1, e.length)
                      .toString()
                      .replaceAll(",", " "),
                  }),
                  Object(o.jsx)(i, {}),
                ],
              });
            }
            return Object(o.jsxs)("div", {
              children: [
                Object(o.jsxs)("p", {
                  children: ["talhajaved.com : command not found: ", t],
                }),
                Object(o.jsx)(i, {}),
              ],
            });
          };
          return Object(o.jsxs)(o.Fragment, {
            children: [
              Object(o.jsxs)("div", {
                style: { display: "flex", flexDirection: "row" },
                children: [
                  Object(o.jsx)("p", { children: "[guest@talhajaved.com]: " }),
                  Object(o.jsx)("input", {
                    disabled: c,
                    onKeyDown: function (i) {
                      Object(d.b)(g, "select_content", {
                        content_type: "image",
                        content_id: "P12453",
                        items: [{ name: "Kittens" }],
                      });
                      var a = JSON.parse(localStorage.getItem("history"));
                      "Enter" === i.key &&
                        (a.push(t),
                        localStorage.setItem("history", JSON.stringify(a)),
                        p(i.target.value),
                        y(!0));
                    },
                    autoFocus: !0,
                    value: t,
                    onChange: function (i) {
                      return r(i.target.value.toLowerCase());
                    },
                    type: "text",
                  }),
                ],
              }),
              c ? p() : null,
            ],
          });
        };
      var w = function () {
        return Object(o.jsxs)("div", {
          className: "App",
          children: [
            Object(o.jsx)(c, {}),
            Object(o.jsx)(k.a, { children: Object(o.jsx)(c, {}) }),
            Object(o.jsx)(p, {}),
          ],
        });
      };
      e.p;
      r.a.render(
        Object(o.jsx)(s.a.StrictMode, { children: Object(o.jsx)(w, {}) }),
        document.getElementById("root")
      );
    },
  },
  [[43, 1, 2]],
]);
